# Generated by Django 5.1.3 on 2024-12-04 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient_recipe_ingredirent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredirent',
            new_name='ingredirents',
        ),
    ]
