# Generated by Django 5.1.3 on 2024-12-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_ingredirent_recipe_ingredirents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredirents',
            new_name='ingredients',
        ),
    ]
